### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by rainerborene** [ryanmjacobs/c#10]
it would be great to have a `--debug` flag to launch `gdb`

**Comment by ryanmjacobs** [comment]
@rainerborene If more people want this, I'll add it. But the script is getting rather large, and I don't want to over complicate it.

**Comment by ellzey** [comment]
working on it.

**Comment by hmocheimech** [comment]
just use  an IDE instead  of UNIX terminals, that's will make thing easier for you

**Comment by natescham** [comment]
wouldn't u have to include the debugger separately?? isn't the compiler / linker / debugger ; whatever, all separate programs.  and is this Ruby script calling an interpreter? to be an interpreter? lol, idk, I am ALL confused now. I gotta dig thru this. It's too late lol...  next on list, learn ruby or python, may help lol.
