### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by slowkow** [ryanmjacobs/c#15]
Hi @ryanmjacobs,

I just want to mention similar work. You might consider adding a link to your readme or taking inspiration from the `~/.c99shrc` config file.

- https://github.com/RhysU/c99sh
- Other nice C stuff: https://notabug.org/koz.ross/awesome-c# (You might want to add your project to the list)

**Comment by ryanmjacobs** [comment]
Thanks @slowkow, I'll look into the use of a config file. However, I really like how simple it is now. It's great to just be able to pass in compiler flags using the shebang.

**Comment by ellzey** [comment]
agree, no config files. just sheebang options!

**Comment by burrows-labs** [comment]
Add to your .bashrc

```
function c {
    if ! [ "$1" ]; then
        echo "'$1' is not a valid name"
        return 1
    fi

    name=`echo "$1" | awk -F . ' { print $1 } '`

    blue='\033[0;34m'
    green='\033[0;32m'
    NC='\033[0m'

    echo -e "${blue}COMPILING${NC}"
    make "$name"

    if [ $? -ne 0 ]; then
        return 1
    fi

    echo -e "\n\n${green}RUNNING${NC}"
    { ./$name ; }
}
```

Add rule to Makefile

```
hello:
	gcc -Wall -pedantic -std=c99 -g hello.c -o hello -lX11 -lXt
```

Then you can do
```
bash$ ls
hello.c Makefile
bash$ c hello.c
COMPILING
gcc -Wall -pedantic -std=c99 -g hello.c -o hello


RUNNING
hello world!
```

https://github.com/burrows-labs/vimrc/blob/master/.bashrc

**Comment by ryanmjacobs** [comment]
@burrows-labs Cool, but the purpose of `c` is to run files with ease. No messing with makefiles, etc. All you need to do is type `c file.c` (or add a shebang to your file).

**Comment by burrows-labs** [comment]
I'd prefer to handle the complexity of a project with multiple files and whatever compiler/linker options in a Makefile.  This let's me do that and still have the ```c``` nicety of compiling/running in one step.

>> Cool, but the purpose of c is to run files with ease.
 
Similarly, this eases the compile/execute process for projects with a Makefile.

**Comment by ellzey** [comment]
Let's not turn this into yet another build system.

Potentially having the first file passed to the script would contain main(),if any other files are passed on the commandline, treeat then as files to compile as objects to link with the first. 

Let me prototype that up real quick

**Comment by alebcay** [comment]
@ryanmjacobs mentioned that `c` is meant to be used with small files/projects. If your project needs a makefile, you probably shouldn't be using `c` - too much stuff could break. If you just want to pass in some cflags, I think you already can do that via the shebang options (correct me if I'm wrong).

Also - what would you do if your makefile had multiple targets? Makefiles aren't meant to be processed by a tool like `c` - they're meant to be used to build relatively large and complex projects. These projects may include source files from other languages, snippets of bash and what not. To feed that all into `c` - well, you might as well rewrite `make` itself.

**Comment by burrows-labs** [comment]
I was imagining scenarios where I have a project layout such as [this](https://github.com/burrows-labs/clipboard). The Makefile has a bunch of executable targets, but everything is still pretty simple.

I want to do this
```
bash$ c exe_target
<compile>
<run>
```

Instead of
```
bash$ make exe_target
compile
bash$ ./obj/exe_target
run
```

[This implementation](https://github.com/burrows-labs/ctwo) accomplishes those goals. Requires ruby because my bashfu wasn't up to the challenge.

**Comment by ellzey** [comment]
You have just described a normal build system with a wrapper script. 

I'd say that this project is done. No new features unless it's something really awesome and keeps things simple as it is now. It's a great way to prototype and should stay that way.

Alternatives have been shown, put them in the readme, and close this issue.

**Comment by burrows-labs** [comment]
> You have just described a normal build system with a wrapper script.

It's like your asking me to argue with you about the semantics of "build systems".

> With this shell script, you can compile and execute C "scripts" in one go!
That's from the ryan-c README.

\<me-thinking\>Could I also compile and execute C code from slightly more complicated projects in one go using a simple script?  What's the best way to do this?\</me-thinking\>

> Alternatives have been shown, put them in the readme, and close this issue.

close/open/whatever, this thread seems like a reasonable place to talk about "scripts that compile and execute C code in one go".

**Comment by ryanmjacobs** [comment]
I agree with @alebcay, if you're using a Makefile, then you shouldn't be using `c` anyways. `c` is just for small "scripts".

I also agree with @ellzey. This project is pretty much done. Unless something simple and awesome comes along, there isn't really much point in adding it.

@burrows-labs If you want to compile *slightly* more complex projects, then just use multiple files and link in the libraries you want. Ex:
```bash
$ c "one_file.c another_file.c -lncurses -lm one_more_file.c" arg1 arg2
```
or do the same thing in the shebang:
```bash
#!/usr/bin/c one_file.c another_file.c -lncurses -lm one_more_file.c --
```
then make it executable and run it.

**Comment by alebcay** [comment]
> Could I also compile and execute C code from slightly more complicated projects in one go using a simple script? What's the best way to do this?

However you choose to do this, with or without `c`, expect dismal results - complicated projects use a build system for a reason. We must also remember that the traditional `Makefile` often performs other processes on the source files in preparation for building. To handle that would require implementing an `m4` parser into `c`, among other things, which simply isn't viable as a shell script - that's why `make` isn't written in shell script.

**Comment by ryanmjacobs** [comment]
> complicated projects use a build system for a reason.

Exactly.

**Comment by ellzey** [comment]
close, create a wiki page, allow users to put in their own build flows using this project; link to other similar work, and be done with it.

**Comment by ryanmjacobs** [comment]
@ellzey Okay, I created a wiki page. I think anyone can edit it now.
