### ISSUE TITLE
-D option isn't present on BSD `install`, causing bpkg install to fail on some systems

### ISSUE THREAD

**Issue by alphabetum** [ryanmjacobs/c#23]
BSD `install` doesn't have the `-D` option, which causes installation to fail on systems that use this version of `install`.

My (probably incomplete) understanding is that this can be resolved by splitting this into a `mkdir -p` followed by `install` sans the `-D` option, but I don't know if there is a better way that works with the bpkg 'install' field.

For reference, the relevant `install` command: https://github.com/ryanmjacobs/c/blob/master/package.json#L6

**Comment by ryanmjacobs** [comment]
@alphabetum Thanks! I took your suggestion of using `mkdir -p`, but I don't know if I need to bump the version number in order for `bpkg` to see it.

**Comment by alphabetum** [comment]
It now installs properly. Thank you!

**Comment by ryanmjacobs** [comment]
Sweet! I'll close this issue now.

**Comment by Jeff-Russ** [comment]
So what exactly do I need to run if i don't have -D?

**Comment by Jeff-Russ** [comment]
Also now that Mac OS X is "root-less" you can't modify `/usr/bin`. I even tried enabling the root user and still no dice.  `/usr/local`, however is allowed so I'll use that I guess.
