### ISSUE TITLE
Support prefixed install in examples

### ISSUE THREAD

**Issue by jdachtera** [ryanmjacobs/c#24]
What do you think about using
```
#!/usr/bin/env c
```
as shebang to support prefixed install. Then you can e.g. install in /usr/local and still run the examples:
```
PREFIX=/usr/local bpkg install ryanmjacobs/c
```

**Comment by ryanmjacobs** [comment]
I really wish we could do this. Someone already asked for it in https://github.com/ryanmjacobs/c/issues/5, but it's just not portable to pass flags to `env`.

Instead, what we could do is:
```
#!../c
```
This would allow users to run the examples without installing. However, then the examples can only be run from the `examples/` directory.

**Comment by jdachtera** [comment]
Ah ok, I didn't know that. But I think prefixed install doesn't really make sense then.
