### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [ryanmjacobs/c#27]
What is the license for this code? I'm interested in it, as I am the maintainer of [awesome-c][1], and would prefer to have license terms to include.

[1]: https://notabug.org/koz.ross/awesome-c

**Comment by ryanmjacobs** [comment]
It's [MIT](https://github.com/ryanmjacobs/c#license).

**Comment by kozross** [comment]
@ryanmjacobs: No problem - I've added it. I aim to be *the* go-to place for C tools, libraries, frameworks etc.

**Comment by ryanmjacobs** [comment]
Cool. I'll close this issue now.
