### ISSUE TITLE
Programs with stdin redirection/piping

### ISSUE THREAD

**Issue by ryanmjacobs** [ryanmjacobs/c#28]
Currently we can't pipe `stdin` input into a C program, e.g.

``` c
#include <stdio.h>

int main(void) {
    char buf[1024];
    while (fgets(buf, 1024, stdin) != NULL) {
        puts(buf);
    }
}
```

``` bash
$ c file.c arg1 arg2 < /dev/urandom
$ ./file.c arg1 arg2 < /dev/urandom
```

Because we use `stdin` for file input, I don't think we can also use it for program input as well. I'm not quite sure how to approach this... maybe we can only choose one or the other?

(btw, `stdin` input without piping works just fine)

``` bash
$ c file.c arg1 arg2
hello
hello

world
world

^C
```

**Comment by mcjohnalds** [comment]
Not the cleanest solution, but one way would be to split it into two programs, `c` and `cin`. Example:

    c file.c arg1 arg2 < /dev/urandom
    cin arg1 arg2 < file.c

A program running with `cin` still can't take stdin, but I think compiling c from a stream is pretty rare anyway.

**Comment by ryanmjacobs** [comment]
Yeah, that is a possibility. But I like only having one script to copy around... And it's kind of nice being able to run something like:
```
$ c << EOF
main() { /* code */ }
```

However, if lots of people want different behavior, then I will probably change it.

---

The ideal solution would be to be able to pass a flag telling `c` to use `stdin` for source code, (and otherwise use `stdin` for the compiled program's input), i.e.
```
$ echo "main() { /* code */ }" | c --stdin
$ echo "hello" | c prog.c
```
... but I don't know how to do that yet.

**Comment by Bruno-Sosa** [comment]
Wouldn't it be enough to change the test at https://github.com/ryanmjacobs/c/blob/master/c#L84 ?

**Comment by ryanmjacobs** [comment]
Removed support for this stdin feature 7f723ae.

See reasons here: [tag/v0.11](https://github.com/ryanmjacobs/c/releases/tag/v0.11).
