### ISSUE TITLE
disabling caching

### ISSUE THREAD

**Issue by xelatihy** [ryanmjacobs/c#33]
While caching is great in general, I found it to be hard if you are developing code in a header file. Is there a way to shut off the caching?

**Comment by ryanmjacobs** [comment]
`export C_CACHE_SIZE=0` should do the trick. If you don't want to clutter up your `ENV`, you can use `alias c='c C_CACHE_SIZE=0'`

Hopefully that helps :)

**Comment by ryanmjacobs** [comment]
Whoops, I meant `alias c='C_CACHE_SIZE=0 c'`

**Comment by xelatihy** [comment]
Great --- thanks!

**Comment by ryanmjacobs** [comment]
@xelatihy Took over a year, but it's fixed :sweat_smile:
