### ISSUE TITLE
du --block-size does not work on MacOS

### ISSUE THREAD

**Issue by GiovanniBussi** [ryanmjacobs/c#38]
Hi,

pretty useful tool. In order to make it work on MacOS I had to make this change:
````
-    size="$(du --block-size=1024 -s "$tmproot" | tail -n1 | cut -f1)"
+    size="$(du -k -s "$tmproot" | tail -n1 | cut -f1)"
````
The reason is that `du` on MacOS does not support `--block-size`. I can try to fix the script to detect MacOS and use `du -k`, but I noticed that this line has been edited in commit 91b66a0d0a0b821c3aa2990e80159785172baba3, so I don't know which is the best solution. 

Thanks!

Giovanni

**Comment by ryanmjacobs** [comment]
Haha right, I forgot about that. Thanks! I just reverted that commit.
