### ISSUE TITLE
Brew

### ISSUE THREAD

**Issue by bruno-** [ryanmjacobs/c#6]
Hi, can we please get this on [brew](http://brew.sh)?

**Comment by ryanmjacobs** [comment]
I've never written a brew formula before. Can someone double check this?

```ruby
require "formula"

class C < Formula
    homepage "https://github.com/ryanmjacobs/c"
    url "https://github.com/ryanmjacobs/c/archive/v0.06.tar.gz"
    sha1 "0eefb3523abccea7ebdd2c56d4d7be6f23585645"

    def install
        system "cp", "./c/c", "#{prefix}/bin"
    end

    test do
        Dir.chdir("tests") do
            system "test.sh"
        end
    end
end
```

**Comment by janten** [comment]
I have written a brew formula and submitted a [pull request](
https://github.com/Homebrew/homebrew/pull/37403).

**Comment by ryanmjacobs** [comment]
@janten Thanks!

**Comment by bruno-** [comment]
Thanks guys, that's great!

**Comment by ellzey** [comment]
on this note, as this project is gaining more attention - `c` may not be the best name for it, I foresee conflicts galore. 

* `crun` (remember brun, fuck I'm old)
* `cbang`

something like that.
