### ISSUE TITLE
sed for shebang fails on OSX 

### ISSUE THREAD

**Issue by jasonkeene** [ryanmjacobs/c#7]
The sed command that removes/replaces the shebang appears to fail on OSX yosemite:

    $ c << EOF
    #include <stdio.h>

    int main()
    {
      printf("Hello World!\n");
      return 0;
    }
    EOF
    sed: 1: "/tmp/c.ox3.stdin.c": command c expects \ followed by text
    Hello World!
    sed: 1: "/tmp/c.ox3.stdin.c": command c expects \ followed by text

**Comment by alebcay** [comment]
Using GNU `sed` will fix the issue temporarily for you until this issue is resolved. `brew install --with-default-names gnu-sed` and then try running it again. It seems that perhaps without `gsed`, the shebang feature may not work, although invoking `c` manually will still work, albeit with error messages.

**Comment by ryanmjacobs** [comment]
@jasonkeene Try it now please.

**Comment by ryanmjacobs** [comment]
I have *completely* removed the use of `sed`. See if it works now.

**Comment by LinusU** [comment]
@ryanmjacobs Could you tag HEAD as `v0.09` please, Homebrew only accepts formulas that points to tagged releases.

**Comment by LinusU** [comment]
Forgot to mention, but I have tested the current `HEAD` and it works great!

**Comment by HongxuChen** [comment]
@ryanmjacobs For shebang, actually I hope you can mention the [zsh suffix alias](http://zshwiki.org/home/examples/aliassuffix), e.g., `alias -s c="c"`, `alias -s c="cpp"`, `alias -s c="cc"`. By using this feature, there is no need for a shebang with `chmod +x` (and that breaks regular compilation, right?), simply `/path/to/single/c/file` is enough.

**Comment by ryanmjacobs** [comment]
@HongxuChen Yes, but not everyone uses zsh. I'll try to mention it in the readme.

**Comment by HongxuChen** [comment]
@ryanmjacobs Yes. And thanks for such a good wrapper.

**Comment by ryanmjacobs** [comment]
@HongxuChen However, using this method you can't use compiler flags. Correct?

**Comment by HongxuChen** [comment]
@ryanmjacobs Yes. So I think perhaps using `CFLAGS`/`CXXFLAGS` is a must.

**Comment by ryanmjacobs** [comment]
I closing this issue because we have dropped the use of sed. This shouldn't be a problem anymore.
